name: Test
on:
    push:
        branches:
        - main
        tags: 
        - 'v*.*.*'
    pull_request:
        branches:
        - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Print concurrency group
              run: |
                echo "Concurrency group: ${{ github.ref != 'refs/heads/pr5' && format('tests-{0}-{1}-{2}', github.ref, github.event_name) || github.sha }}"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.24.2
            - name: Run Tests
              run: |
                go install gotest.tools/gotestsum@latest
                gotestsum --format testname --junitfile=junit.xml -- -v ./...
            - name: Upload Test Results to Trunk.io
              if: ${{ !cancelled() }}
              uses: trunk-io/analytics-uploader@main
              with:
                junit-paths: "**/junit.xml"        
                org-slug: adam-test
                token: ${{ secrets.TRUNK_TOKEN }}
